### ISSUE TITLE
先把文章写起来，别老是折腾什么theme

### ISSUE THREAD

**Issue by pygyme** [liuymzz/liuymzz.github.io#4]
有点东西啊   并发编程

**Comment by pygyme** [comment]
明啊，好像去年就是这么一篇， 今年都快过完了，没点新的东西。。。。。。。。。。

**Comment by liuymzz** [comment]
哈哈哈，折腾永不停歇，之前的theme不喜欢，想换个简洁的

**Comment by liuymzz** [comment]
> 明啊，好像去年就是这么一篇， 今年都快过完了，没点新的东西。。。。。。。。。。

这篇是今年的
